version: '3.1'

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: fc_challenge
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-data/:/var/lib/mysql

  api:
    build: 
      dockerfile: ./nodejsdockerfile
    depends_on: 
     - db
    entrypoint: wait-for db:3306 -t 40 -- node index.js
    volumes:
      - ./index.js:/app/index.js

  nginx:
    build: 
      dockerfile: ./nginxdockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
